const actions = {
  SET_CURRENT_ROUTE: 'SET_CURRENT_ROUTE',
  RESET_REDIRECT: 'RESET_REDIRECT',
  SET_REDIRECT: 'SET_REDIRECT',
  SET_ORDER_UPDATE_INTERVAL: 'SET_ORDER_UPDATE_INTERVAL',
  RESET_ORDER_UPDATE_INTERVAL: 'RESET_ORDER_UPDATE_INTERVAL',

  FETCH_ORDERS: 'FETCH_ORDERS',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAILED: 'FETCH_ORDERS_FAILED',
};

export default actions;
